---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes
  namespace: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      name: hello-kubernetes
  template:
    metadata:
      labels:
        name: hello-kubernetes
    spec:
      containers:
      - name: app
        image: paulbouwer/hello-kubernetes:1.10.1
        ports:
          - containerPort: 8080
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
---

apiVersion: v1
kind: Service
metadata:
  namespace: myapp
  name: hello-kubernetes
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP #NodePort
  ports:
    - port: 80
      targetPort: 8080
      name: tcp
  selector:
    name: hello-kubernetes