prometheus:
       prometheusSpec:
              serviceMonitorSelectorNilUsesHelmValues: false
              podMonitorSelectorNilUsesHelmValues: false
              serviceMonitorNamespaceSelector:
                     matchLabels:
                            prometheus: "true"
