prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector:
      matchLabels:
        prometheus: "true"
coreDns:
  enabled: false
alertmanager:
  enabled: true
  alertmanagerSpec:
    useExistingSecret: true
    secrets:
      - alertmanager-kube-prometheus-stack-alertmanager


